### ISSUE TITLE
Not able to figure out how it works the app

### ISSUE THREAD

**Issue by Redidacove** [TheBojda/zktree-vote#3]
I understood that we have to first use the register for vote option and copy the commitment .
But after that how as a voter am I getting the nullifier and then if I go to vote just shows options to vote for no need for anything there so how will voting happen if I just vote for it it doesn't works that way .

And what is validator tool used for like I did used it from acc 1 of hardhat which was the validator as you said then will the validator have to take commitment from voter for it and then what to put in unique hash and then when I hit on send to blockchain then it sometimes and then sometimes error shows .

Can you plz make a video or describe here how to use your application and how voting is conducted through it really new to zk thing so plz forgive me for asking this

**Comment by Redidacove** [comment]
Ohk thnks a lot for such a wonderful explanation.
Just love your articles they are super informative and helpful

**Comment by Redidacove** [comment]
Can you plz share your linkedin or discord wanna ask more doubts around it as I am building something using your libraries. Here won't be a good place to ask I believe

**Comment by Redidacove** [comment]
Hey When I go and validate from validator acc giving the commitment hash generated by a voter acc and proceed to do the transaction it fails to do so telling undefined alert and in metamask something like 

`Rpc error  in message "Trying to send a raw transaction with an invalid chainId" The expected chainId is 31337 `

But I have configured hardhat with 31337 only don't know why it's happening

**Comment by TheBojda** [comment]
It's not zktree related, but check this: https://hardhat.org/hardhat-network/docs/metamask-issue

**Comment by Redidacove** [comment]
![error ss](https://github.com/TheBojda/zktree-vote/assets/114795592/6d5993c3-a864-44f0-b557-dd373ff10ae5)

**Comment by Redidacove** [comment]
when trying to vote for any option after validation

**Comment by TheBojda** [comment]
It is hard to say from this, what is the root of the problem. If you can log the params of calculateMerkleRootAndZKProof, maybe I can say something.

Is the contract successfully deployed?

**Comment by Redidacove** [comment]
Contract is deployed but how will I be able to log the params of calculateMerkleRootAndZkProof

**Comment by TheBojda** [comment]
It is enough if you log the commitment parameter. Is it generated successfully, and stored in localstore?

**Comment by TheBojda** [comment]
Hmm. I can reproduce the error, but don't know the source of it yet. When you register the voter's commitment by the validator tool, hardhat node throws some error (you can see it on the console), this is why you cannot vote.

`npx hardhat test` works fine, so the problem only appears if you use it with hardhat node and metamask. It worked fine before, so something changed somewhere.

Try to find out what...

**Comment by TheBojda** [comment]
I've updated some dependencies, and now it works for me. Take a try with it.

**Comment by jsidorenko** [comment]
This error happens if you try to vote before registering the commitment. When you submit your vote it fails to calculate the root hash as there are no records onchain.

**Comment by Redidacove** [comment]
Got it
