### ISSUE TITLE
Vote function in ZKTreeVote 

### ISSUE THREAD

**Issue by Bagdu** [TheBojda/zktree-vote#4]
Hello in Vote function in ZKTreeVote.sol you simply executing this code `optionCounter[_option] = optionCounter[_option] + 1`. Doesn't this mean that i can extract that msg.sender gives the vote to _option, if i see the transaction on blockchain.

**Comment by TheBojda** [comment]
Yes. You have to use a different Ethereum address to vote and register yourself. In the case of ZKTreeVote, the users are registered by the validators. 

Btw, if you want you can generate an Ethereum wallet for voting, and throw it away after it.

**Comment by Bagdu** [comment]
Ok,  Thank you, i got it after i wrote it :D.
Can also you help me on this, in this https://github.com/TheBojda/zktree-vote/blob/main/contracts/Verifier.sol -  `verifyingKey()` - where did you get the point values? is it a known algorithm or something, where i can find this values ? I really want to understand whole math behind this contract, so can i find papers or something to get where this G1,G2.. Values came from.

**Comment by TheBojda** [comment]
It is generated by snarkjs. Check the prepare script here: https://github.com/TheBojda/zktree-vote/blob/main/scripts/prepare.sh#L9C1-L9C83

I wrote articles about the practical use of ZKP, which you can find here: https://medium.com/better-programming/understanding-zero-knowledge-proofs-through-the-source-code-of-tornado-cash-41d335c5475f

But it is not about the math. There are many articles on the web about the math of zkSNARKs. For example, you can start with Vitalik's blog: https://vitalik.ca/general/2021/01/26/snarks.html

**Comment by Bagdu** [comment]
Many thanks, and if someone steals `static/verifier.zkey` file, is there any chance to falsify the zkproofs of vote, Or deployer can get the voters actual vote with this file ? Is this a risk ?

**Comment by TheBojda** [comment]
No, zkey is public, and generated from the circuit and the ptau file. If the ptau file is reliable, then everything is safe.

But check the snarkjs docs here: https://github.com/iden3/snarkjs

You can find all the info about the zkey, ptau, etc. files here.
