### ISSUE TITLE
eth_maxPriorityFeePerGas - Method not supported

### ISSUE THREAD

**Issue by daizhiwei123456** [TheBojda/zktree-vote#5]
When running the command to start Hardhat node (npx hardhat node), an error message is displayed indicating eth_maxPriorityFeePerGas-Method is not supported. What can I do

**Comment by daizhiwei123456** [comment]
![20231128093618](https://github.com/TheBojda/zktree-vote/assets/127122285/ef391045-e139-47a9-a626-8aa4a74bd032)

**Comment by TheBojda** [comment]
I cannot reproduce this bug. 

Btw, `npx hardhat node` is simply starting a virtual blockchain that is not related to the project. Is it working fine outside of the project?

**Comment by daizhiwei123456** [comment]
Sorry author, my statement may not be very clear. When smart contract npm run deploy is deployed on another terminal, the preceding error occurs on the Hardhat node. There is no error when the Hardhat node npx hardhat node is started simply in the project directory. This error may also cause gas not to be calculated in metamask user transfers as shown below:

**Comment by daizhiwei123456** [comment]
![20231128153232](https://github.com/TheBojda/zktree-vote/assets/127122285/9f2a7e41-947e-4839-a71d-24f26694cab8)
![Uploading 20231128153356.png…]()

**Comment by TheBojda** [comment]
Looks like a MetaMask <-> HardHat error. Could you please try this: https://hardhat.org/hardhat-network/docs/metamask-issue

**Comment by daizhiwei123456** [comment]
thank you very much

**Comment by daizhiwei123456** [comment]
Hello, I'm sorry to bother you. I am a beginner in replicating your code is the following problem how to solve?
![20231129101941](https://github.com/TheBojda/zktree-vote/assets/127122285/def81fae-cc52-4f6c-a693-7d3377cb576d)
![20231129101954](https://github.com/TheBojda/zktree-vote/assets/127122285/1aae2d97-8e13-4fa1-8e53-4254d852e987)

**Comment by TheBojda** [comment]
To call the registerCommitment (https://github.com/TheBojda/zktree-vote/blob/31e55db22f7a86985994d081bc1828ca3b038705/contracts/ZKTreeVote.sol#L29) the caller account has to be registered by registerValidator (https://github.com/TheBojda/zktree-vote/blob/31e55db22f7a86985994d081bc1828ca3b038705/contracts/ZKTreeVote.sol#L24C14-L24C31).

Currently, the deploy.ts registers the 2nd hardhat account as validator (https://github.com/TheBojda/zktree-vote/blob/31e55db22f7a86985994d081bc1828ca3b038705/scripts/deploy.ts#L23), but you can change this.

So, if you don't change anything, you should use the 2nd account to use the validator tool and register the commitment.

**Comment by daizhiwei123456** [comment]
cool！
